### ISSUE TITLE
URLs not correctly sorted in index?

### ISSUE THREAD

**Issue by wiseman** [trivio/common_crawl_index#15]
I think I found incorrectly sorted URLs in the index.  For example, in block 4, net.about-plumbing.www/... comes after net.absolutely.www/...:

```
  'my.com.mahsuri.www/blog/rawatan/ti\x00',
  'name.armando.francesco.www/gallery/andrea_e_vera/slides/DSCN4325\x00',
  'net.123tools.www/audio_multimedia/audio_file_players/index-n-123tools-3\x00',
+ 'net.about-plumbing.www/new-hampshire/colebrook-m\x00',
  "net.absolutely.www/event/Premiere_of_'Land_of_the_Lost'/land_of_the_lost_02_wenn24377\x00",
- 'net.about-plumbing.www/new-hampshire/colebrook-m\x00',
  'net.adiochiropractic.www/templates20/article/1296\x00',
  'net.agilpage.www/index~m~1~w~11276\x00',
  'net.alblasserdam.www/nieuws/2009-07-02-6051-internetprovider-proserve-bouwt-regionaal-datacenter-in-alblasserdam.html:http\x00',
```

(The above is a diff of the actual list of prefixes in the block and the sorted list of prefixes in the block.)

This could cause a failure of the bisection lookup.

**Comment by srobertson** [comment]
Interesting, I've had a few reports of this. On thing that jumps out is the
entrie has double quotes one it while all the other output has single. Is
this an artifact of you hand editing when putting the example together?

On Thu, Mar 21, 2013 at 5:18 PM, John Wiseman notifications@github.comwrote:

> I think I found incorrectly sorted URLs in the index. For example, in
> block 4, net.about-plumbing.www/... comes after net.absolutely.www/...:
> 
>   'my.com.mahsuri.www/blog/rawatan/ti\x00',
>   'name.armando.francesco.www/gallery/andrea_e_vera/slides/DSCN4325\x00',
>   'net.123tools.www/audio_multimedia/audio_file_players/index-n-123tools-3\x00',
> - 'net.about-plumbing.www/new-hampshire/colebrook-m\x00',
>   "net.absolutely.www/event/Premiere_of_'Land_of_the_Lost'/land_of_the_lost_02_wenn24377\x00",
> - 'net.about-plumbing.www/new-hampshire/colebrook-m\x00',
>   'net.adiochiropractic.www/templates20/article/1296\x00',
>   'net.agilpage.www/index~m~1~w~11276\x00',
>   'net.alblasserdam.www/nieuws/2009-07-02-6051-internetprovider-proserve-bouwt-regionaal-datacenter-in-alblasserdam.html:http\x00',
> 
> This could cause a failure of the bisection lookup.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/trivio/common_crawl_index/issues/15
> .

## 

-- Scott

"There was a time when the internet answered all my questions. Now it just
repeats them. - SDR"

**Comment by wiseman** [comment]
Those are python strings printed using `pprint`, so yeah it's an artifact of that (and that the URL printed with double quotes contains single quotes).

**Comment by srobertson** [comment]
Cool thanks! Sorry for all those typos. Was replying from an iphone.

On Thu, Mar 21, 2013 at 5:58 PM, John Wiseman notifications@github.comwrote:

> Those are python strings printed using pprint, so yeah it's an artifact
> of that (and that the URL printed with double quotes contains single
> quotes).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/trivio/common_crawl_index/issues/15#issuecomment-15275682
> .

## 

-- Scott

"There was a time when the internet answered all my questions. Now it just
repeats them. - SDR"
