### ISSUE TITLE
 ImportError: No module named boto

### ISSUE THREAD

**Issue by danielnicollet** [trivio/common_crawl_index#17]
Hello,
I am experimenting with your Python script which seems very promising for a separate project requiring lookups of Common Crawl URLs.  I have installed your current version from Git on my Ubuntu machine and ran:

`
   $ bin/index_lookup_remote france.fr
    Traceback (most recent call last):
      File "bin/index_lookup_remote", line 26, in <module>
        import boto
    ImportError: No module named boto
`
Can you please tell me what `boto` is supposed to be?
Thanks,
Dan

**Comment by srobertson** [comment]
Boto is the the python library for working with s3.

You can install it with a command python's package manager "pip" on unix
platforms it's something like this

$ pip install boto

On Sat, Apr 13, 2013 at 9:29 AM, danielnicollet notifications@github.comwrote:

> Hello,
> I am experimenting with your Python script which seems very promising for
> a separate project requiring lookups of Common Crawl URLs. I have installed
> your current version from Git on my Ubuntu machine and ran:
> 
> $ bin/index_lookup_remote france.fr
> Traceback (most recent call last):
> File "bin/index_lookup_remote", line 26, in <module>
> import boto
> ImportError: No module named boto
> 
> Can you please tell me what boto is supposed to be?
> Thanks,
> Dan
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/trivio/common_crawl_index/issues/17
> .

## 

-- Scott

"There was a time when the internet answered all my questions. Now it just
repeats them. - SDR"

**Comment by danielnicollet** [comment]
Hi,
wow - that was fast and yes - I did indeed find that myself in the meantime.
By now you gathered I am a python hack/beginner :)
Dan

**Comment by srobertson** [comment]
Welcome!

On Sat, Apr 13, 2013 at 9:36 AM, danielnicollet notifications@github.comwrote:

> Hi,
> wow - that was fast and yes - I did indeed find that myself in the
> meantime.
> By now you gathered I am a python hack/beginner :)
> Dan
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/trivio/common_crawl_index/issues/17#issuecomment-16336216
> .

## 

-- Scott

"There was a time when the internet answered all my questions. Now it just
repeats them. - SDR"

**Comment by danielnicollet** [comment]
Thanks - by the way, you mention in your post here:
http://jronallo.github.io/blog/common-crawl-url-index/
that script is able to access the URL index anonymously.
Is that still the case?
I get:
`return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'anon'
`

**Comment by srobertson** [comment]
You need the latest version of boto, or aws keys

On Sat, Apr 13, 2013 at 9:49 AM, danielnicollet notifications@github.comwrote:

> Thanks - by the way, you mention in your post here:
> http://jronallo.github.io/blog/common-crawl-url-index/
> that script is able to access the URL index anonymously.
> Is that still the case?
> I get:
> return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
> TypeError: **init**() got an unexpected keyword argument 'anon'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/trivio/common_crawl_index/issues/17#issuecomment-16336458
> .

## 

-- Scott

"There was a time when the internet answered all my questions. Now it just
repeats them. - SDR"

**Comment by danielnicollet** [comment]
Strange - I did install boto before I got the error...

**Comment by danielnicollet** [comment]
Here is the full run output:
`
$ bin/index_lookup_remote france.fr
Traceback (most recent call last):
  File "bin/index_lookup_remote", line 64, in <module>
    '/common-crawl/projects/url-index/url-index.1356128792'
  File "bin/index_lookup_remote", line 33, in __init__
    self.conn  = boto.connect_s3(anon=True)
  File "/usr/lib/python2.7/dist-packages/boto/__init__.py", line 107, in connect_s3
    return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'anon'
`

**Comment by srobertson** [comment]
You need the latests version of boto 2.5.2. What version did you install?

On Sat, Apr 13, 2013 at 10:06 AM, danielnicollet
notifications@github.comwrote:

> Here is the full run output:
> 
> $ bin/index_lookup_remote france.fr
> Traceback (most recent call last):
> File "bin/index_lookup_remote", line 64, in <module>
> '/common-crawl/projects/url-index/url-index.1356128792'
> File "bin/index_lookup_remote", line 33, in **init**
> 
> self.conn = boto.connect_s3(anon=True)
> File "/usr/lib/python2.7/dist-packages/boto/**init**.py", line 107, in
> connect_s3
> return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
> TypeError: **init**() got an unexpected keyword argument 'anon'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/trivio/common_crawl_index/issues/17#issuecomment-16336739
> .

## 

-- Scott

"There was a time when the internet answered all my questions. Now it just
repeats them. - SDR"

**Comment by danielnicollet** [comment]
Thanks for your help.  You were correct.  OK, so I checked and indeed my version of Ubuntu being a little old, I had an older version of Python and boto as well.
