### ISSUE TITLE
./remote_read www.direkt-einkauf.at does not return anything

### ISSUE THREAD

**Issue by keiw** [trivio/common_crawl_index#3]
The reason i believe it should return something is:

```
url -r 1048584-1048744 http://s3.amazonaws.com/aws-publicdatasets/common-crawl/projects/url-index/url-index.1356128792 
```

which is the second index block, which contains prefixes for this domain

**Comment by srobertson** [comment]
The hostnames are stored in reversed url order.

./remote_read   at.direkt-einkauf.www

Because of this you can also search for all urls that start with

"at.direkt-einkau"

or even

"at"

**Comment by keiw** [comment]
Thank you. 
Saw a reversed url order in the storage itself though my expectation was that the query mechanism would allow for direct queries i.e ".com" or "google.com" or "news.google.com"

Do you think it is worth mentioning at docs or may be ./read_remote script could apply backward reverse url transformation?

**Comment by srobertson** [comment]
The docs should defiantly mention it.

On Fri, Jan 11, 2013 at 7:46 PM, keiw notifications@github.com wrote:

> Thank you.
> Saw a reversed url order in the storage itself though my expectation was
> that the query mechanism would allow for direct queries i.e ".com" or "
> google.com" or "news.google.com"
> 
> Do you think it is worth mentioning at docs or may be ./read_remote script
> could apply backward reverse url transformation?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/trivio/common_crawl_index/issues/3#issuecomment-12173023.

## 

-- Scott

"There was a time when the internet answered all my questions. Now it just
repeats them. - SDR"
